name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}
        tags: latest
        labels: latest
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: user/app:latest
